Sync of paired devices once permissions are given (#138)
# Sync of paired devices once permissions are given

## :recycle: Current situation & Problem
@Basler182 noticed a crash after deleting and reinstalling the app,
where Bluetooth permissions are lost. The issue was related to the
paired devices storage component that was attempting to sync on init.
Adapting syncing of devices after we have guaranteed in BLEService that
the permissions are given. Crash stacktrace

```

java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@b445b3e6: AdapterService getBondedDevices
at android.os.Parcel.createExceptionOrNull(Parcel.java:3242)
at android.os.Parcel.createException(Parcel.java:3226)
at android.os.Parcel.readException(Parcel.java:3209)
at android.os.Parcel.readException(Parcel.java:3151)
at android.bluetooth.IBluetooth$Stub$Proxy.getBondedDevices(IBluetooth.java:2622)
at android.bluetooth.BluetoothAdapter.getBondedDevices(BluetoothAdapter.java:2818)
at edu.stanford.spezi.core.bluetooth.domain.BLEPairedDevicesStorage.refreshState(BLEPairedDevicesStorage.kt:54)
at edu.stanford.spezi.core.bluetooth.domain.BLEPairedDevicesStorage.<init>(BLEPairedDevicesStorage.kt:35)
```


## :gear: Release Notes 
*Add a bullet point list summary of the feature and possible migration
guides if this is a breaking change so this section can be added to the
release notes.*
*Include code snippets that provide examples of the feature implemented
or links to the documentation if it appends or changes the public
interface.*


## :books: Documentation
*Please ensure that you properly document any additions in conformance
to [Spezi Documentation
Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).*
*You can use this section to describe your solution, but we encourage
contributors to document your reasoning and changes using in-line
documentation.*


## :white_check_mark: Testing
*Please ensure that the PR meets the testing requirements set by CodeCov
and that new functionality is appropriately tested.*
*This section describes important information about the tests and why
some elements might not be testable.*


## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code
of
Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md)
and [Contributing
Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of
Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md)
and [Contributing
Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

---------

Co-authored-by: Kilian Schneider <48420258+Basler182@users.noreply.github.com>